/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import com.mxrck.autocompleter.TextAutoCompleter;
import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JYearChooser;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sapu
 */
public class AdminStaff_Attendance extends javax.swing.JFrame {

    /**
     * Creates new form AdminStaff_Attendance
     */
    public AdminStaff_Attendance() {
        initComponents();
        
        auto_completer();
    }
    
    
    private void clear(){
    
        txt_emp_name.setText("");
        txt_empid.setText("");
        txt_worked_days.setText("");
      
    }

    private void get_data_to_table() {

        try {

            Statement st = DbConnection.getconnection().createStatement();
            ResultSet rs = st.executeQuery("  select * from emp_atten_admin_staff where Month='" + cmb_month.getSelectedItem().toString() + "' and Year='" + cmb_year.getSelectedItem().toString() + "' ");

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            while (rs.next()) {

                Vector v = new Vector();

                v.add(rs.getString("EPFno"));
                v.add(rs.getString("Name"));
                v.add(rs.getString("WorkedDays"));

                dtm.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }

    private void auto_completer() {

        try {

            Statement st = DbConnection.getconnection().createStatement();
            ResultSet rs = st.executeQuery("select * from employee_reg where IsResigned=0 and RankCategory='Admin Staff' ");

            TextAutoCompleter ta = new TextAutoCompleter(txt_emp_name);

            while (rs.next()) {
                String code = rs.getString("EPFno");
                String NameWithInitials = rs.getString("NameWithInitials");

                ta.addItem(code);
                ta.addItem(NameWithInitials);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txt_emp_name = new javax.swing.JTextField();
        txt_empid = new javax.swing.JTextField();
        cmb_year = new javax.swing.JComboBox();
        cmb_month = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_worked_days = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel1.setText("Admin Staff Attendance");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 40));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 550, 10));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setText("  Employee  :-");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 20));

        txt_emp_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_emp_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emp_nameKeyPressed(evt);
            }
        });
        getContentPane().add(txt_emp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 290, 23));

        txt_empid.setEditable(false);
        txt_empid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txt_empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 100, 23));

        cmb_year.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        cmb_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020" }));
        cmb_year.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_yearPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cmb_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        cmb_month.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        cmb_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cmb_month.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_monthPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cmb_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setText("Month / Year  :-");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EPF no", "Employee Name", "Worked Days"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(23);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(400);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 530, 230));

        txt_worked_days.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_worked_days.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_worked_daysKeyPressed(evt);
            }
        });
        getContentPane().add(txt_worked_days, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 80, 23));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel9.setText("Worked Days  :-");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jButton3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save 1.png"))); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 110, -1));

        jButton4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 110, -1));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 550, 10));

        jButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eraser.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emp_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_nameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {

                Statement st = DbConnection.getconnection().createStatement();
                ResultSet rs = st.executeQuery("select * from employee_reg where EPFno='" + txt_emp_name.getText() + "' or NameWithInitials='" + txt_emp_name.getText() + "'");
                while (rs.next()) {

                    txt_emp_name.setText(rs.getString("NameWithInitials"));
                    txt_empid.setText(rs.getString("EPFno"));

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_txt_emp_nameKeyPressed

    private void cmb_yearPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_yearPopupMenuWillBecomeInvisible

        get_data_to_table();
        clear();

        //        int mm = cmb_month.getSelectedIndex();
        //        int int_month = mm + 1;
        //        String month = String.format("%02d", int_month);
        //
        //        String year = cmb_year.getSelectedItem().toString();
        //        int int_year = Integer.parseInt(year);
        //
        //        String d1 = (year + "-" + month + "-" + "01");
        //        String d2 = (year + "-" + month + "-" + "02");
        //        String d3 = (year + "-" + month + "-" + "03");
        //        String d4 = (year + "-" + month + "-" + "04");
        //        String d5 = (year + "-" + month + "-" + "05");
        //        String d6 = (year + "-" + month + "-" + "06");
        //        String d7 = (year + "-" + month + "-" + "07");
        //        String d8 = (year + "-" + month + "-" + "08");
        //        String d9 = (year + "-" + month + "-" + "09");
        //        String d10 = (year + "-" + month + "-" + "10");
        //        String d11 = (year + "-" + month + "-" + "11");
        //        String d12 = (year + "-" + month + "-" + "12");
        //        String d13 = (year + "-" + month + "-" + "13");
        //        String d14 = (year + "-" + month + "-" + "14");
        //        String d15 = (year + "-" + month + "-" + "15");
        //        String d16 = (year + "-" + month + "-" + "16");
        //        String d17 = (year + "-" + month + "-" + "17");
        //        String d18 = (year + "-" + month + "-" + "18");
        //        String d19 = (year + "-" + month + "-" + "19");
        //        String d20 = (year + "-" + month + "-" + "20");
        //        String d21 = (year + "-" + month + "-" + "21");
        //        String d22 = (year + "-" + month + "-" + "22");
        //        String d23 = (year + "-" + month + "-" + "23");
        //        String d24 = (year + "-" + month + "-" + "24");
        //        String d25 = (year + "-" + month + "-" + "25");
        //        String d26 = (year + "-" + month + "-" + "26");
        //        String d27 = (year + "-" + month + "-" + "27");
        //        String d28 = (year + "-" + month + "-" + "28");
        //        String d29 = (year + "-" + month + "-" + "29");
        //        String d30 = (year + "-" + month + "-" + "30");
        //        String d31 = (year + "-" + month + "-" + "31");
        //
        //        String d1d = "0";
        //        String d2d = "0";
        //        String d3d = "0";
        //        String d4d = "0";
        //        String d5d = "0";
        //        String d6d = "0";
        //        String d7d = "0";
        //        String d8d = "0";
        //        String d9d = "0";
        //        String d10d = "0";
        //        String d11d = "0";
        //        String d12d = "0";
        //        String d13d = "0";
        //        String d14d = "0";
        //        String d15d = "0";
        //        String d16d = "0";
        //        String d17d = "0";
        //        String d18d = "0";
        //        String d19d = "0";
        //        String d20d = "0";
        //        String d21d = "0";
        //        String d22d = "0";
        //        String d23d = "0";
        //        String d24d = "0";
        //        String d25d = "0";
        //        String d26d = "0";
        //        String d27d = "0";
        //        String d28d = "0";
        //        String d29d = "0";
        //        String d30d = "0";
        //        String d31d = "0";
        //
        //        String d1n = "0";
        //        String d2n = "0";
        //        String d3n = "0";
        //        String d4n = "0";
        //        String d5n = "0";
        //        String d6n = "0";
        //        String d7n = "0";
        //        String d8n = "0";
        //        String d9n = "0";
        //        String d10n = "0";
        //        String d11n = "0";
        //        String d12n = "0";
        //        String d13n = "0";
        //        String d14n = "0";
        //        String d15n = "0";
        //        String d16n = "0";
        //        String d17n = "0";
        //        String d18n = "0";
        //        String d19n = "0";
        //        String d20n = "0";
        //        String d21n = "0";
        //        String d22n = "0";
        //        String d23n = "0";
        //        String d24n = "0";
        //        String d25n = "0";
        //        String d26n = "0";
        //        String d27n = "0";
        //        String d28n = "0";
        //        String d29n = "0";
        //        String d30n = "0";
        //        String d31n = "0";
        //
        //        String d1h = "0";
        //        String d2h = "0";
        //        String d3h = "0";
        //        String d4h = "0";
        //        String d5h = "0";
        //        String d6h = "0";
        //        String d7h = "0";
        //        String d8h = "0";
        //        String d9h = "0";
        //        String d10h = "0";
        //        String d11h = "0";
        //        String d12h = "0";
        //        String d13h = "0";
        //        String d14h = "0";
        //        String d15h = "0";
        //        String d16h = "0";
        //        String d17h = "0";
        //        String d18h = "0";
        //        String d19h = "0";
        //        String d20h = "0";
        //        String d21h = "0";
        //        String d22h = "0";
        //        String d23h = "0";
        //        String d24h = "0";
        //        String d25h = "0";
        //        String d26h = "0";
        //        String d27h = "0";
        //        String d28h = "0";
        //        String d29h = "0";
        //        String d30h = "0";
        //        String d31h = "0";
        //
        //        try {
        //
        //            Statement st = DbConnection.getconnection().createStatement();
        //
        //            ResultSet rs = st.executeQuery("select LocName,Location, Date, SUM(DayShift),SUM(NightShift),SUM(HalfDayShift) from `location_reg`INNER JOIN `emp_atten_main`  ON location_reg.`LocCode` = emp_atten_main.`Location` where Month='February' group by Date");
        //
        //            //ResultSet rs = st.executeQuery("SELECT Location, Date, SUM(DayShift),SUM(NightShift),SUM(HalfDayShift) FROM `location_reg`INNER JOIN `emp_atten_main`  ON location_reg.`LocCode` = emp_atten_main.`Location`  WHERE MONTH='" + cmb_month.getSelectedItem().toString() + "' GROUP BY Date ");
        //            while (rs.next()) {
        //
        //                String Date = rs.getString("Date");
        //
        //                if (Date.equals(d1)) {
        //
        //                    d1d = rs.getString("SUM(DayShift)");
        //                    d1n = rs.getString("SUM(NightShift)");
        //
        //                    String half = rs.getString("SUM(HalfDayShift)");
        //                    Double halfday = Double.parseDouble(half);
        //
        //                    d1h = Double.toString(halfday / 2);
        //
        //                }
        //                if (Date.equals(d2)) {
        //
        //                    d2d = rs.getString("SUM(DayShift)");
        //                    d2n = rs.getString("SUM(NightShift)");
        //
        //                    String half = rs.getString("SUM(HalfDayShift)");
        //                    Double halfday = Double.parseDouble(half);
        //
        //                    d2h = Double.toString(halfday / 2);
        //
        //                }
        //                if (Date.equals(d3)) {
        //
        //                    d3d = rs.getString("SUM(DayShift)");
        //                    d3n = rs.getString("SUM(NightShift)");
        //
        //                    String half = rs.getString("SUM(HalfDayShift)");
        //                    Double halfday = Double.parseDouble(half);
        //
        //                    d3h = Double.toString(halfday / 2);
        //
        //                }
        //
        //                String LocCode = rs.getString("Location");
        //                String LocName = rs.getString("LocName");
        //
        //                System.out.println(LocCode);
        //                System.out.println(LocName);
        //
        //                bean_ateen_summery bds = new bean_ateen_summery();
        //
        //                bds.setL_code(LocCode);
        //                bds.setL_name(LocName);
        //
        //                bds.setDay1day(d1d);
        //                bds.setDay1night(d1n);
        //                bds.setDay1half(d1h);
        //
        //                bds.setDay2day(d2d);
        //                bds.setDay2night(d2n);
        //                bds.setDay2half(d2h);
        //
        //                atten_sum.add(bds);
        //            }
        //
        //            print();
        //
        //        } catch (Exception e) {
        //            e.printStackTrace();
        //        }
    }//GEN-LAST:event_cmb_yearPopupMenuWillBecomeInvisible

    private void txt_worked_daysKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_worked_daysKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_worked_daysKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (txt_empid.getText().isEmpty() || txt_emp_name.getText().isEmpty() || txt_worked_days.getText().isEmpty()) {

        } else {

            try {

                Statement st = DbConnection.getconnection().createStatement();
                st.executeUpdate("insert into emp_atten_admin_staff values ('" + txt_empid.getText() + "','" + cmb_month.getSelectedItem().toString() + "','" + cmb_year.getSelectedItem().toString() + "','" + txt_worked_days.getText() + "','" + txt_emp_name.getText() + "')");

                JOptionPane.showMessageDialog(rootPane, " Saved...! ");
                get_data_to_table();
                clear();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
                e.printStackTrace();
            }

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            Statement st = DbConnection.getconnection().createStatement();
            st.executeUpdate("delete from emp_atten_admin_staff where EPFno='" + txt_empid.getText() + "' and  Month='" + cmb_month.getSelectedItem().toString() + "' and Year='" + cmb_year.getSelectedItem().toString() + "' ");

            JOptionPane.showMessageDialog(rootPane, " Deleted...! ");

            get_data_to_table();
            clear();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e);
        }

//        int year = Integer.parseInt(cmb_year.getSelectedItem().toString());
//        int days = 0;
//        
//        if (cmb_month.getSelectedItem().toString().equals("January")) {
//            
//            days = 31;
//            
//        } else if (cmb_month.getSelectedItem().toString().equals("February")) {
//            
//            if (year % 4 == 0) {
//                if (year % 100 == 0) {
//                    if (year % 400 == 0) {
//                        //System.out.println(year + " Is A LEAP YEAR");
//                        days = 29;
//                    } else {
//                        //System.out.println(year + " Is NOT LEAP YEAR");
//                        days = 28;
//                    }
//                } else {
//                    //System.out.println(year + " Is A LEAP YEAR");
//                    days = 29;
//                }
//            } else {
//                //System.out.println(year + " Is NOT LEAP YEAR");
//                days = 28;
//            }
//            
//        } else if (cmb_month.getSelectedItem().toString().equals("March")) {
//            
//            days = 31;
//            
//        } else if (cmb_month.getSelectedItem().toString().equals("April")) {
//            
//            days = 30;
//            
//        } else if (cmb_month.getSelectedItem().toString().equals("May")) {
//            
//            days = 31;
//            
//        } else if (cmb_month.getSelectedItem().toString().equals("June")) {
//            
//            days = 30;
//            
//        } else if (cmb_month.getSelectedItem().toString().equals("July")) {
//            
//            days = 31;
//            
//        } else if (cmb_month.getSelectedItem().toString().equals("August")) {
//            
//            days = 31;
//            
//        } else if (cmb_month.getSelectedItem().toString().equals("September")) {
//            
//            days = 30;
//            
//        } else if (cmb_month.getSelectedItem().toString().equals("October")) {
//            
//            days = 31;
//            
//        } else if (cmb_month.getSelectedItem().toString().equals("November")) {
//            
//            days = 30;
//            
//        } else if (cmb_month.getSelectedItem().toString().equals("December")) {
//            
//            days = 31;
//            
//        }
//        
//        System.out.println(cmb_month.getSelectedItem().toString() + " " + days);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmb_monthPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_monthPopupMenuWillBecomeInvisible
        get_data_to_table(); 
        clear();// TODO add your handling code here:
    }//GEN-LAST:event_cmb_monthPopupMenuWillBecomeInvisible

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {

            int row = jTable1.getSelectedRow();
            String table_click = jTable1.getModel().getValueAt(row, 0).toString();

            Statement st = DbConnection.getconnection().createStatement();
            ResultSet rs = st.executeQuery("select * from emp_atten_admin_staff where EPFno='" + table_click + "' and Month='" + cmb_month.getSelectedItem().toString() + "' and Year='" + cmb_year.getSelectedItem().toString() + "' ");

            while (rs.next()) {

                txt_empid.setText(rs.getString("EPFno"));
                txt_emp_name.setText(rs.getString("Name"));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStaff_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStaff_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStaff_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStaff_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStaff_Attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_month;
    private javax.swing.JComboBox cmb_year;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_emp_name;
    private javax.swing.JTextField txt_empid;
    private javax.swing.JTextField txt_worked_days;
    // End of variables declaration//GEN-END:variables
}
