/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Sapumal Bandara @ TechSeed Solutions
 */
public class Invoice_Deduc_and_Add extends javax.swing.JFrame {

    /**
     * Creates new form Invoice_Deduc_and_Add
     */
    public Invoice_Deduc_and_Add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txt_LocCode = new javax.swing.JTextField();
        txt_LocName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_LocOwnerName = new javax.swing.JTextField();
        txt_LocOwnerName1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_LocOwnerName2 = new javax.swing.JTextField();
        txt_LocOwnerName3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmb_month = new javax.swing.JComboBox();
        cmb_year = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel1.setText("Invoice Adjustments");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 40));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 830, 10));

        txt_LocCode.setEditable(false);
        txt_LocCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_LocCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_LocCodeFocusLost(evt);
            }
        });
        txt_LocCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LocCodeActionPerformed(evt);
            }
        });
        txt_LocCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_LocCodeKeyPressed(evt);
            }
        });
        getContentPane().add(txt_LocCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 60, -1));

        txt_LocName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_LocName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LocNameActionPerformed(evt);
            }
        });
        txt_LocName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_LocNameKeyPressed(evt);
            }
        });
        getContentPane().add(txt_LocName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 300, -1));

        jLabel19.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel19.setText("Amount :-");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        txt_LocOwnerName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_LocOwnerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_LocOwnerNameFocusGained(evt);
            }
        });
        txt_LocOwnerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LocOwnerNameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_LocOwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 140, -1));

        txt_LocOwnerName1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_LocOwnerName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_LocOwnerName1FocusGained(evt);
            }
        });
        txt_LocOwnerName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LocOwnerName1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_LocOwnerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 300, -1));

        jLabel20.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel20.setText("Month / Year :-");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel21.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel21.setText("Description :-");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        jButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Minus-30.png"))); // NOI18N
        jButton1.setText("Remove Addition");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jButton2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        jButton2.setText("Save");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        txt_LocOwnerName2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_LocOwnerName2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_LocOwnerName2FocusGained(evt);
            }
        });
        txt_LocOwnerName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LocOwnerName2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_LocOwnerName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 140, -1));

        txt_LocOwnerName3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_LocOwnerName3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_LocOwnerName3FocusGained(evt);
            }
        });
        txt_LocOwnerName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LocOwnerName3ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_LocOwnerName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 300, -1));

        jLabel22.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel22.setText("Description :-");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 20));

        jLabel23.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel23.setText("Amount :-");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 20));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Invoice Addtions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 12))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 430, 140));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Invoice Deductions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 12))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 430, 120));

        cmb_month.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        cmb_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(cmb_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, -1));

        cmb_year.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        cmb_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020" }));
        cmb_year.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_yearPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cmb_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel24.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel24.setText("Location :-");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Addition Description", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 350, 120));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Deduction Description", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 350, 120));

        jButton3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        jButton3.setText("Save");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jButton4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Minus-30.png"))); // NOI18N
        jButton4.setText("Remove Deduction");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_LocCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_LocCodeFocusLost
        //        String code = txt_LocCode.getText();
        //
        //        try {
            //            Statement st = DbConnection.getconnection().createStatement();
            //            ResultSet rs = st.executeQuery("select * from location_reg");
            //
            //            while (rs.next()) {
                //                String LocCode = rs.getString("LocCode");
                //
                //                if (code.equals(LocCode)) {
                    //                    btn_LocSave.setEnabled(false);
                    //                } else {
                    //
                    //                }
                //            }
            //
            //        } catch (Exception e) {
            //        }
    }//GEN-LAST:event_txt_LocCodeFocusLost

    private void txt_LocCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LocCodeActionPerformed
        txt_LocName.grabFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocCodeActionPerformed

    private void txt_LocCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_LocCodeKeyPressed
        //(evt.getKeyCode() == KeyEvent.VK_F1  && evt.isControlDown()

            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                String code = txt_LocName.getText();

                try {
                    Statement st = DbConnection.getconnection().createStatement();
                    ResultSet rs = st.executeQuery("select * from location_reg where LocCode='" + txt_LocCode.getText() + "' OR LocName='" + txt_LocCode.getText() + "'");

                    while (rs.next()) {

//                        btn_LocSave.setEnabled(false);
                        txt_LocCode.setText(rs.getString("LocCode"));
                        txt_LocName.setText(rs.getString("LocName"));
//                        txt_LocAddress.setText(rs.getString("LocAddress"));
//                        txt_LocTele1.setText(rs.getString("Tel1"));
//                        txt_LocTel2.setText(rs.getString("Tel2"));
//                        txt_LocTel3.setText(rs.getString("Tel3"));
//                        txt_LocCity.setText(rs.getString("City"));
//                        txt_LocDistrict.setText(rs.getString("District"));
//                        txt_LocIncharge.setText(rs.getString("LocInchargeName"));
//                        txt_LocOwnerName.setText(rs.getString("LocOwnerName"));
//                        txt_LocOwnerTel.setText(rs.getString("LocOwnerTel"));
//                        txt_ShiftRate.setText(rs.getString("LocOwnerMobile"));
//                        cmb_locType.setSelectedItem(rs.getString("LocType"));

//                        String Status = rs.getString("LocStatus");
//                        if (Status.equals("1")) {
//                            jCheckBox2.setSelected(true);
//                        } else {
//                            jCheckBox2.setSelected(false);
//                        }
//                        Loc_Status();
                    }
//
//                    DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
//                    dtm.setRowCount(0);
//
//                    Statement st1 = DbConnection.getconnection().createStatement();
//                    ResultSet rs1 = st1.executeQuery("select * from location_shift_rates where LocCode = '" + txt_LocCode.getText() + "'");
//
//                    while (rs1.next()) {
//
//                        Vector v = new Vector();
//                        v.add(rs1.getString("Rank"));
//                        v.add(rs1.getString("ShiftRate"));
//
//                        dtm.addRow(v);
//                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
    }//GEN-LAST:event_txt_LocCodeKeyPressed

    private void txt_LocNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LocNameActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocNameActionPerformed

    private void txt_LocNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_LocNameKeyPressed
        //          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //
            //            String name = txt_LocName.getText();
            //
            //            try {
                //                Statement st = DbConnection.getconnection().createStatement();
                //                ResultSet rs = st.executeQuery("select * from location_reg");
                //
                //                while (rs.next()) {
                    //                    String LocName = rs.getString("LocName");
                    //
                    //                    if (name.equals(LocName)) {
                        //                        btn_LocSave.setEnabled(false);
                        //
                        //                        txt_LocCode.setText(rs.getString("LocCode"));
                        //                        txt_LocAddress.setText(rs.getString("LocAddress"));
                        //                        txt_LocTele1.setText(rs.getString("Tel1"));
                        //                        txt_LocTel2.setText(rs.getString("Tel2"));
                        //                        txt_LocTel3.setText(rs.getString("Tel3"));
                        //                        txt_LocCity.setText(rs.getString("City"));
                        //                        txt_LocDistrict.setText(rs.getString("District"));
                        //                        txt_LocIncharge.setText(rs.getString("LocInchargeName"));
                        //                        txt_LocOwnerName.setText(rs.getString("LocOwnerName"));
                        //                        txt_LocOwnerTel.setText(rs.getString("LocOwnerTel"));
                        //                        txt_ShiftRate.setText(rs.getString("LocOwnerMobile"));
                        //                        cmb_locType.setSelectedItem(rs.getString("LocType"));
                        //
                        //                    } else {
                        //
                        //                    }
                    //                }
                //                DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
                //                dtm.setRowCount(0);
                //
                //                Statement st1 = DbConnection.getconnection().createStatement();
                //                ResultSet rs1 = st1.executeQuery("select * from location_shift_rates where LocCode = '" + txt_LocCode.getText() + "'");
                //
                //                while (rs1.next()) {
                    //
                    //                    Vector v = new Vector();
                    //                    v.add(rs1.getString("Rank"));
                    //                    v.add(rs1.getString("ShiftRate"));
                    //
                    //                    dtm.addRow(v);
                    //                }
                //
                //            } catch (Exception e) {
                //                e.printStackTrace();
                //            }
            //
            //        }
    }//GEN-LAST:event_txt_LocNameKeyPressed

    private void txt_LocOwnerNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_LocOwnerNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocOwnerNameFocusGained

    private void txt_LocOwnerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LocOwnerNameActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocOwnerNameActionPerformed

    private void txt_LocOwnerName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_LocOwnerName1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocOwnerName1FocusGained

    private void txt_LocOwnerName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LocOwnerName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocOwnerName1ActionPerformed

    private void txt_LocOwnerName2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_LocOwnerName2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocOwnerName2FocusGained

    private void txt_LocOwnerName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LocOwnerName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocOwnerName2ActionPerformed

    private void txt_LocOwnerName3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_LocOwnerName3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocOwnerName3FocusGained

    private void txt_LocOwnerName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LocOwnerName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocOwnerName3ActionPerformed

    private void cmb_yearPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_yearPopupMenuWillBecomeInvisible
        //        int month = 0;
        //        month = cmb_month.getSelectedIndex();
        //        String year = cmb_year.getSelectedItem().toString();
        //
        //        if (month == 11) {
            //
            //            month = 0;
            ////            Object m1 = cmb_month.getItemAt(month);
            ////            System.out.println(m1);
            ////            System.out.println("0" + (month + 1));
            //
            //            int x = Integer.parseInt(year);
            //            int nextYear = x + 1;
            //
            //            lbl_startDate.setText(nextYear + "-" + ("0" + (month + 1)) + "-" + "01");
            //            lbl_endDate.setText(nextYear + "-" + ("0" + (month + 1)) + "-" + "10");
            //
            //        } else {
            //            int next = month + 2;
            //            String nextM = Integer.toString(next);
            //            int len = nextM.length();
            //
            ////            Object mm = cmb_month.getItemAt(month + 1);
            ////            System.out.println(mm);
            //            if (len == 1) {
                ////                System.out.println("0" + nextM);
                //
                //                lbl_startDate.setText(year + "-" + ("0" + (nextM)) + "-" + "01");
                //                lbl_endDate.setText(year + "-" + ("0" + (nextM)) + "-" + "10");
                //
                //            } else {
                ////                System.out.println(nextM);
                //                lbl_startDate.setText(year + "-" + ((nextM)) + "-" + "01");
                //                lbl_endDate.setText(year + "-" + ((nextM)) + "-" + "10");
                //
                //            }
            //
            //        }
    }//GEN-LAST:event_cmb_yearPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice_Deduc_and_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice_Deduc_and_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice_Deduc_and_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice_Deduc_and_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice_Deduc_and_Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_month;
    private javax.swing.JComboBox cmb_year;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_LocCode;
    private javax.swing.JTextField txt_LocName;
    private javax.swing.JTextField txt_LocOwnerName;
    private javax.swing.JTextField txt_LocOwnerName1;
    private javax.swing.JTextField txt_LocOwnerName2;
    private javax.swing.JTextField txt_LocOwnerName3;
    // End of variables declaration//GEN-END:variables
}
