/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class Location_poyaday extends javax.swing.JFrame {

    /**
     * Creates new form Location_poyaday
     */
    public Location_poyaday() {
        initComponents();
        get_Location_Details();
    }
    
    ArrayList<table_data> al = new ArrayList<table_data>();
    
    private void clear() {
        cmb_EffectiveRank.setSelectedItem("");
        cmb_defLocation.setSelectedItem("=Location=");
        txt_locName.setText("");
        txt_amt.setText("");
        cmb_EffectiveRank.removeAllItems();
        
        int nrow = jTable1.getModel().getRowCount();
        if (nrow == 0) {
            
        } else {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            al.clear();
        }
        
    }
    
    private void get_Location_Details() {
        try {
            
            Statement st = DbConnection.getconnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * from location_reg order by LocName");
            
             AutoCompleteDecorator.decorate(cmb_defLocation);
            
            while (rs.next()) {

                //  Object name = rs.getString("LocName");
                Object code = rs.getString("LocName");
                
                cmb_defLocation.addItem(code);
                //cmb_defLocation.addItem(name);
            }
            
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txt_locName = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        txt_amt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cmb_EffectiveRank = new javax.swing.JComboBox();
        cmb_defLocation = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel1.setText("Poya Day -  Shift Rates - Location Wise");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 40));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 460, 10));

        txt_locName.setEditable(false);
        txt_locName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_locName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_locNameFocusGained(evt);
            }
        });
        getContentPane().add(txt_locName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 73, 320, 23));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Plus-30.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        txt_amt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_amt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_amtFocusGained(evt);
            }
        });
        getContentPane().add(txt_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, 25));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setText("Amount per Day");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 110, 20));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Location", "Rank", "per Day Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 310, 220));

        jButton3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save 1.png"))); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 110, -1));

        jButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eraser.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jButton4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 110, -1));

        cmb_EffectiveRank.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        cmb_EffectiveRank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "==Effective Rank==" }));
        cmb_EffectiveRank.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_EffectiveRankPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cmb_EffectiveRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 25));

        cmb_defLocation.setEditable(true);
        cmb_defLocation.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmb_defLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=Location=" }));
        cmb_defLocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb_defLocationFocusGained(evt);
            }
        });
        cmb_defLocation.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_defLocationPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cmb_defLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 320, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setText("Location:-");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 40));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 460, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_locNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_locNameFocusGained

    }//GEN-LAST:event_txt_locNameFocusGained

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (txt_amt.getText().isEmpty() | txt_locName.getText().isEmpty()) {
        } else {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            Vector v = new Vector();
            
            table_data t = new table_data();
            t.poya_rank = cmb_EffectiveRank.getSelectedItem().toString();
            t.poya_Loc = cmb_defLocation.getSelectedItem().toString();
            t.poya_Amount = txt_amt.getText();
            
            al.add(t);
            
            v.add(cmb_defLocation.getSelectedItem().toString());
            v.add(cmb_EffectiveRank.getSelectedItem().toString());
            v.add(txt_amt.getText());
            
            dtm.addRow(v);
            
            txt_amt.setText("");
            
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_amtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_amtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_amtFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int nrow = jTable1.getModel().getRowCount();
        
        if (nrow == 0) {
            JOptionPane.showMessageDialog(rootPane, " No Data to Save...!");
        } else {
            try {
                
                Statement st = DbConnection.getconnection().createStatement();
                for (table_data t : al) {
                    st.executeUpdate("insert into location_poyaday_rates values ('" + t.poya_Loc + "','" + t.poya_rank + "','" + t.poya_Amount + "')");
                }
                
                JOptionPane.showMessageDialog(rootPane, " Shift Rates Saved...!");
                
                clear();
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        
        int nrow = jTable1.getModel().getRowCount();
        
        if (nrow == 0) {
        } else {
            String loc = jTable1.getModel().getValueAt(row, 0).toString();
            String rank = jTable1.getModel().getValueAt(row, 1).toString();
            String amount = jTable1.getModel().getValueAt(row, 2).toString();
            
            try {
                
                Statement st = DbConnection.getconnection().createStatement();
                st.executeUpdate("delete from location_poyaday_rates where LocCode = '" + loc + "' and Rank ='" + rank + "' and PoyaDayAmt = '" + amount + "'  ");
                
                JOptionPane.showMessageDialog(rootPane, " Selected Data Deleted... ");
                
                dtm.removeRow(row);
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clear();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmb_EffectiveRankPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_EffectiveRankPopupMenuWillBecomeInvisible

    }//GEN-LAST:event_cmb_EffectiveRankPopupMenuWillBecomeInvisible

    private void cmb_defLocationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb_defLocationFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_defLocationFocusGained

    private void cmb_defLocationPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_defLocationPopupMenuWillBecomeInvisible
        
        if (cmb_defLocation.getSelectedItem().equals("=Location=")) {
            
            txt_locName.setText("** Please Select a Location ");
            txt_locName.setForeground(Color.red);
            
        } else {
            txt_locName.setForeground(Color.black);
            try {
                
                cmb_EffectiveRank.removeAllItems();
                cmb_EffectiveRank.addItem("==Effective Rank==");
                
                
                Statement st = DbConnection.getconnection().createStatement();
                ResultSet rs = st.executeQuery("SELECT * from location_reg where LocCode= '" + cmb_defLocation.getSelectedItem().toString() + "'  OR LocName='" + cmb_defLocation.getSelectedItem().toString() + "' ");
                while (rs.next()) {
                    
                    String code = rs.getString("LocCode");
                    String name = rs.getString("LocName");
                    
                    cmb_defLocation.setSelectedItem(code);
                    txt_locName.setText(name);
                }
                
                ResultSet rs1 = st.executeQuery("select * from location_shift_rates where LocCode= '" + cmb_defLocation.getSelectedItem().toString() + "' ");
                
                while (rs1.next()) {
                    
                    String rank = rs1.getString("Rank");
                    
                    cmb_EffectiveRank.addItem(rank);
                    
                }
                
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
                ResultSet rs2 = st.executeQuery("select * from location_poyaday_rates where LocCode= '" + cmb_defLocation.getSelectedItem().toString() + "' ");
                
                while (rs2.next()) {
                    
                    String rank = rs2.getString("Rank");
                    String amount = rs2.getString("PoyaDayAmt");
                    String loc = rs2.getString("LocCode");
                    
                    Vector v = new Vector();
                    
                    v.add(loc);
                    v.add(rank);
                    v.add(amount);
                    
                    dtm.addRow(v);
                    
                }

                //                cmb_defLocation.setEditable(false);
                //                cmb_defLocation.setEnabled(false);
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_cmb_defLocationPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Location_poyaday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Location_poyaday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Location_poyaday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Location_poyaday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Location_poyaday().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_EffectiveRank;
    private javax.swing.JComboBox cmb_defLocation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_amt;
    private javax.swing.JTextField txt_locName;
    // End of variables declaration//GEN-END:variables
}
