package Frames;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * TECHSEED SOLUTIONS
 *
 * @author Sapumal Bandara @ TechSeed Solutions
 */
public class PopUp_Emp_Table extends javax.swing.JFrame {

    /**
     * Creates new form PopUp_Emp_Table
     */
    public PopUp_Emp_Table() {
        initComponents();
        POPUP_EMP_TABLE.getTableHeader().setUI(null);
        TitleBar();
    }

    private void TitleBar() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("techseed.png")));
    }

    private void get_emp() {

        String title = this.getTitle();

        int row = POPUP_EMP_TABLE.getSelectedRow();
        String empno = POPUP_EMP_TABLE.getValueAt(row, 0).toString();

        if (title.equals("Advance")) {

            Advance_RASS.txt_ADVANCE_empName.setText(empno);
            Advance_RASS.txt_ADVANCE_empName.grabFocus();

        } else if (title.equals("Attendance")) {
            EMP_Atten_NEW.txt_search.setText(empno);
            EMP_Atten_NEW.txt_search.grabFocus();

        } else if (title.equals("Emp. Reg.")) {

            employee_reg.txt_EmployeeNo.setText(empno);
            employee_reg.txt_EmployeeNo.grabFocus();

        } else if (title.equals("RLIST")) {

            Salary_stop_Payment.txt_RLIST_empName.setText(empno);
            Salary_stop_Payment.txt_RLIST_empName.grabFocus();

        }else if (title.equals("UNIFORM")) {

            Uniform_Deduction_Entry.txt_uniform_empName.setText(empno);
            Uniform_Deduction_Entry.txt_uniform_empName.grabFocus();

        } else {

        }

        this.dispose();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        POPUP_EMP_TABLE = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        POPUP_EMP_TABLE.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        POPUP_EMP_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EMP No", "Employee Name", "Location", "Location Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        POPUP_EMP_TABLE.setRowHeight(25);
        POPUP_EMP_TABLE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                POPUP_EMP_TABLEKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(POPUP_EMP_TABLE);
        if (POPUP_EMP_TABLE.getColumnModel().getColumnCount() > 0) {
            POPUP_EMP_TABLE.getColumnModel().getColumn(0).setResizable(false);
            POPUP_EMP_TABLE.getColumnModel().getColumn(0).setPreferredWidth(10);
            POPUP_EMP_TABLE.getColumnModel().getColumn(1).setResizable(false);
            POPUP_EMP_TABLE.getColumnModel().getColumn(1).setPreferredWidth(200);
            POPUP_EMP_TABLE.getColumnModel().getColumn(2).setPreferredWidth(10);
            POPUP_EMP_TABLE.getColumnModel().getColumn(3).setResizable(false);
            POPUP_EMP_TABLE.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 760, 160));

        jButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Plus-30.png"))); // NOI18N
        jButton1.setText("Select Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 390, 50));

        jButton2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancel.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 260, 50));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setText("|    EMP No       |                                    Employee Name                       |                                          Location                                                               |");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        get_emp();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void POPUP_EMP_TABLEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_POPUP_EMP_TABLEKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            get_emp();

        }         // TODO add your handling code here:
    }//GEN-LAST:event_POPUP_EMP_TABLEKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//*************************Developed By TechSeed Solutions*************************************************
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUp_Emp_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUp_Emp_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUp_Emp_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUp_Emp_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUp_Emp_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable POPUP_EMP_TABLE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
