/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sapumal Bandara
 */
public class POPWINDOW_Employee extends javax.swing.JFrame {

    /**
     * Creates new form POPWINDOW_Employee
     */
    public POPWINDOW_Employee() {
        initComponents();
        tbl_empSearch.getTableHeader().setUI(null);
    }

    public String empSearch(KeyEvent evt, String getText) {

        try {

            Connection con = DbConnection.getconnection();

            String empno = getText;

            String sql = "SELECT * FROM employee_reg WHERE  Surname LIKE ? OR EmployeeNo Like? OR NameWithInitials Like?   ";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, empno + "%");
            pst.setString(2, empno + "%");
            pst.setString(3, empno + "%");
            ResultSet rst = pst.executeQuery();

            DefaultTableModel dtm = (DefaultTableModel) tbl_empSearch.getModel();
            dtm.setRowCount(0);

            while (rst.next()) {

                Vector v = new Vector();
                v.add(rst.getString("EPFno"));
                v.add(rst.getString("NameWithInitials"));
                v.add(rst.getString("Surname"));
                v.add(rst.getString("Designation"));
                v.add(rst.getString("BasicSalary"));

                dtm.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e);
        }

        return null;
        // return null;
    }

    String code = "";
    String name = "";
    String basic = "";
    String rank = "";

    JTextField textbox1;

    public String return_names(JTextField textbox) {
        String ret = "";
        textbox1 = textbox;
        int row = tbl_empSearch.getSelectedRow();
        code = tbl_empSearch.getValueAt(row, 0).toString();
        name = tbl_empSearch.getValueAt(row, 1).toString();
        basic = tbl_empSearch.getValueAt(row, 4).toString();
        rank = tbl_empSearch.getValueAt(row, 3).toString();

        //            txt_search.setText(code);
        ret = code + "|" + name;

        // this.setVisible(false);
        textbox.setText(name);
        textbox.grabFocus();

        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_empSearch = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 255, 51));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_empSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl_empSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "emp", "initials", "surname", "rank", "Basic"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_empSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_empSearch.setRowHeight(23);
        tbl_empSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_empSearchKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_empSearch);
        if (tbl_empSearch.getColumnModel().getColumnCount() > 0) {
            tbl_empSearch.getColumnModel().getColumn(0).setResizable(false);
            tbl_empSearch.getColumnModel().getColumn(0).setPreferredWidth(60);
            tbl_empSearch.getColumnModel().getColumn(1).setPreferredWidth(150);
            tbl_empSearch.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbl_empSearch.getColumnModel().getColumn(3).setResizable(false);
            tbl_empSearch.getColumnModel().getColumn(3).setPreferredWidth(40);
            tbl_empSearch.getColumnModel().getColumn(4).setMinWidth(0);
            tbl_empSearch.getColumnModel().getColumn(4).setPreferredWidth(0);
            tbl_empSearch.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_empSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_empSearchKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.setVisible(false);
//            jScrollPane4.setVisible(false);
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            return_names(textbox1);

//            jScrollPane4.setVisible(false);
        }
//        if (evt.getKeyCode() == KeyEvent.VK_UP) {
//
//            if (tbl_empSearch.getSelectedRow() == 0) {
//                tbl_empSearch.setVisible(false);
//                jScrollPane4.setVisible(false);
//
//            }
//
//        }
    }//GEN-LAST:event_tbl_empSearchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POPWINDOW_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POPWINDOW_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POPWINDOW_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POPWINDOW_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POPWINDOW_Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable tbl_empSearch;
    // End of variables declaration//GEN-END:variables
}
