/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import static Frames.RPT_Deductions.deductions;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sapu
 */
public class RPT_Cash_Denomination extends javax.swing.JFrame {

    /**
     * Creates new form RPT_Cash_Denomination
     */
    static ArrayList denominaion;

    public RPT_Cash_Denomination() {
        initComponents();

        denominaion = new ArrayList();
    }

    static String table = "salary_final";
    static String Query = "";

    void print() {
        try {
            JRBeanCollectionDataSource bcds = new JRBeanCollectionDataSource(denominaion);
            String path = "Reports\\Cash_Denomination.jrxml";//Attendance_Summery_Single_Loc
            JasperReport jr = JasperCompileManager.compileReport(path);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, bcds);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        cmb_month = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        cmb_year = new javax.swing.JComboBox();
        cmb_emp_type = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 360, 10));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel1.setText("Cash Denomination - On Net Salary");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 40));

        cmb_month.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        cmb_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(cmb_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 100, -1));

        jLabel18.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel18.setText("Salary Month / Year :-");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        cmb_year.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        cmb_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        cmb_year.setSelectedIndex(6);
        cmb_year.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_yearPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cmb_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 70, -1));

        cmb_emp_type.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        cmb_emp_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "All Guards (SSS)", "Bank Guards (SSS)", "Non-Bank Guards (SSS)", "Admin Staff", "SIKURA Guards", "Director Staff" }));
        cmb_emp_type.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_emp_typePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cmb_emp_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel11.setText("Employee Type:-");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, 40));

        jButton4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fine Print.png"))); // NOI18N
        jButton4.setText("View ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 290, -1));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_yearPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_yearPopupMenuWillBecomeInvisible
        // set_date_range();
    }//GEN-LAST:event_cmb_yearPopupMenuWillBecomeInvisible

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (cmb_emp_type.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(rootPane, " Please Select an Employee Type ");

        } else {

            String EPF = "";
            String sal = "";

            int F_five_thou = 0;
            int F_one_thou = 0;
            int F_five_hun = 0;
            int F_one_hun = 0;
            int F_fifty = 0;
            int F_twenty = 0;
            int F_ten = 0;
            int F_five = 0;
            int F_two = 0;
            int F_one = 0;
            Double F_cents = 0.00;
            int totalCents = 0;

            try {

                Statement st = DbConnection.getconnection().createStatement();
                ResultSet rs = st.executeQuery(Query);

                while (rs.next()) {

                    EPF = rs.getString("EPFno");

                    Statement st1 = DbConnection.getconnection().createStatement();
                    ResultSet rs1 = st1.executeQuery("select * from `" + table + "` where EPFno='" + EPF + "' and Month='" + cmb_month.getSelectedItem().toString() + "' and Year='" + cmb_year.getSelectedItem().toString() + "' order by EPFno");

                    while (rs1.next()) {

                        sal = rs.getString("NetSalary");

                        Double net_sal = Double.parseDouble(sal);

                        //5000
                        int five_thou = (int) (net_sal / 5000.00);
                        Double bal_five_thou = net_sal - (five_thou * 5000);

                        //1000
                        int thou = (int) (bal_five_thou / 1000.00);
                        Double bal_thou = bal_five_thou - (thou * 1000);

                        //500
                        int five_hun = (int) (bal_thou / 500.00);
                        Double bal_five_hun = bal_thou - (five_hun * 500);

                        //100
                        int hun = (int) (bal_five_hun / 100.00);
                        Double bal_hun = bal_five_hun - (hun * 100);

                        //50
                        int fifty = (int) (bal_hun / 50.00);
                        Double bal_fifty = bal_hun - (fifty * 50);

                        //20
                        int twenty = (int) (bal_fifty / 20.00);
                        Double bal_twenty = bal_fifty - (twenty * 20);

                        //10
                        int ten = (int) (bal_twenty / 10.00);
                        Double bal_ten = bal_twenty - (ten * 10);

                        //5
                        int five = (int) (bal_ten / 5.00);
                        Double bal_five = bal_ten - (five * 5);

                        //2
                        int two = (int) (bal_five / 2.00);
                        Double bal_two = bal_five - (two * 2);

                        //1
                        int one = (int) (bal_two / 1.00);
                        Double bal_one = bal_two - (one * 1);

                        System.out.println(EPF + " NetSal:" + sal + " 5000s:" + five_thou + " 1000s:" + thou + " 500s:" + five_hun + " 100s:" + hun + " 50s" + fifty + " 20s" + twenty + " 10s:" + ten + " 5s:" + five + " 2s:" + two + " 1s:" + one + " bal:" + bal_one);

                        F_five_thou += five_thou;
                        F_one_thou += thou;
                        F_five_hun += five_hun;
                        F_one_hun += hun;
                        F_fifty += fifty;
                        F_twenty += twenty;
                        F_ten += ten;
                        F_five += five;
                        F_two += two;
                        F_one += one;
                        F_cents += bal_one;

                    }

                }
                System.out.println("total 5000s" + F_five_thou);
                System.out.println("total 1000s" + F_one_thou);
                System.out.println("total 500s" + F_five_hun);
                System.out.println("total 100s" + F_one_hun);
                System.out.println("total 50s" + F_fifty);
                System.out.println("total 20s" + F_twenty);
                System.out.println("total 10s" + F_ten);
                System.out.println("total 5s" + F_five);
                System.out.println("total 2s" + F_two);
                System.out.println("total 1s" + F_one);
                System.out.println("total cents" + F_cents);
                //System.out.println("Ents in INT" + totalCents);

//                String centt = String.format("%.2f", F_cents);
//                System.out.println(centt);
//                totalCents = Integer.parseInt(centt);

                double d = F_cents+1.00;
                totalCents = (int) d;
                System.out.println("Cents in INT" + totalCents);

                bean_cash_denomination bds = new bean_cash_denomination();

                bds.setFive_thousand(F_five_thou);
                bds.setOne_thousand(F_one_thou);
                bds.setFive_hundred(F_five_hun);
                bds.setOne_hundred(F_one_hun);
                bds.setFifty(F_fifty);
                bds.setTwenty(F_twenty);
                bds.setTen(F_ten);
                bds.setFive(F_five);
                bds.setTwo(F_two);
                bds.setOne(F_one);
                bds.setCents(F_cents);
                bds.setCentsamount(totalCents);

                bds.setMonth(cmb_month.getSelectedItem().toString());
                bds.setYear(cmb_year.getSelectedItem().toString());
                bds.setEmp_cat(cmb_emp_type.getSelectedItem().toString());

                denominaion.add(bds);

                print();

                denominaion.clear();

                F_five_thou = 0;
                F_one_thou = 0;
                F_five_hun = 0;
                F_one_hun = 0;
                F_fifty = 0;
                F_twenty = 0;
                F_ten = 0;
                F_five = 0;
                F_two = 0;
                F_one = 0;
                F_cents = 0.00;
                totalCents=0;

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmb_emp_typePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_emp_typePopupMenuWillBecomeInvisible
        if (cmb_emp_type.getSelectedIndex() == 0) {

        }
        if (cmb_emp_type.getSelectedIndex() == 1) {

            table = "salary_final";
            Query = ("select * from `" + table + "` where Month='" + cmb_month.getSelectedItem().toString() + "' and Year='" + cmb_year.getSelectedItem().toString() + "' order by EPFno");
        }
        if (cmb_emp_type.getSelectedIndex() == 2) {

            table = "salary_final";
            Query = ("select * from `" + table + "` where Month='" + cmb_month.getSelectedItem().toString() + "' and Year='" + cmb_year.getSelectedItem().toString() + "' and LocationType='Bank' order by EPFno");

        }
        if (cmb_emp_type.getSelectedIndex() == 3) {

            table = "salary_final";
            Query = ("select * from `" + table + "` where Month='" + cmb_month.getSelectedItem().toString() + "' and Year='" + cmb_year.getSelectedItem().toString() + "' and LocationType='Other' order by EPFno");

        }
        if (cmb_emp_type.getSelectedIndex() == 4) {

            table = "salary_final_admin_staff";
            Query = ("select * from `" + table + "` where Month='" + cmb_month.getSelectedItem().toString() + "' and Year='" + cmb_year.getSelectedItem().toString() + "' AND EmpType='director' order by EPFno");

        }
        if (cmb_emp_type.getSelectedIndex() == 5) {

            table = "salary_final_sikura_staff";
            Query = ("select * from `" + table + "` where Month='" + cmb_month.getSelectedItem().toString() + "' and Year='" + cmb_year.getSelectedItem().toString() + "' order by EPFno");

        }if (cmb_emp_type.getSelectedIndex() == 6) {

            table = "salary_final_admin_staff";
            Query = ("select * from `" + table + "` where Month='" + cmb_month.getSelectedItem().toString() + "' and Year='" + cmb_year.getSelectedItem().toString() + "' AND EmpType='director' order by EPFno");

        }


    }//GEN-LAST:event_cmb_emp_typePopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPT_Cash_Denomination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPT_Cash_Denomination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPT_Cash_Denomination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPT_Cash_Denomination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPT_Cash_Denomination().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_emp_type;
    private javax.swing.JComboBox cmb_month;
    private javax.swing.JComboBox cmb_year;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
