/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Sapu
 */
public class RPT_Earnings extends javax.swing.JFrame {

    /**
     * Creates new form RPT_Deductions
     */
    static ArrayList deductions;

    PreparedStatement pst;
    Connection con;

    public RPT_Earnings() {
        initComponents();
        deductions = new ArrayList();

        TitleBar();
        get_Location_Details();

    }

    private void TitleBar() {
        this.setTitle("Monthly Earning Reports");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("techseed.png")));
    }

    private void get_Location_Details() {
        try {

            Statement st = DbConnection.getconnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * from location_reg order by LocName");

            while (rs.next()) {

                Object name = rs.getString("LocName");
                //Object code = rs.getString("LocCode");

                // cmb_defLocation.addItem(code);
                cmb_defLocation.addItem(name);
            }

            AutoCompleteDecorator.decorate(cmb_defLocation);

        } catch (Exception e) {
        }

    }

    String EPFno = null;
    String EmpName = null;
    String Sal_Adv_01 = null;
    String Sal_Adv_02 = null;
    String Loan01 = null;
    String Loan02 = null;
    String Uniform = null;
    String Shoe = null;
    String welfare = null;
    String meal = null;
    String fine = null;
    String rental = null;
    String less_shift = null;
    String other_deduc = null;
    String death = null;
    String paid10 = null;
    String insuarance = null;
    String festival = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        cmb_month1 = new javax.swing.JComboBox();
        cmb_year1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        cmb_earn_type = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmb_emp_type = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmb_defLocation = new javax.swing.JComboBox();
        txt_locCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel2.setText("Monthly Earnings Reports");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 40));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 630, 10));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 640, 10));

        jLabel20.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Month & Year :  ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 28));

        cmb_month1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cmb_month1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cmb_month1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_month1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cmb_month1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 160, 28));

        cmb_year1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cmb_year1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2020", "2021", "2022", "2023" }));
        cmb_year1.setSelectedIndex(2);
        cmb_year1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_year1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cmb_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 70, 28));

        jLabel19.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Eaning Type :  ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 28));

        cmb_earn_type.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        cmb_earn_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "==SELECT==", "ALL", "Machine Allowance", "Special Allowance", "Attendance Allowance", "Other Allowance", "Additional Shift Amount", "Poya" }));
        cmb_earn_type.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_earn_typePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cmb_earn_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 480, 28));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Employee Type :  ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 28));

        cmb_emp_type.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        cmb_emp_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL", "Site Staff (Guard)", "Admin Staff", "Director Staff" }));
        cmb_emp_type.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_emp_typePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cmb_emp_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 480, 28));

        jButton4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/New Icons/icons8_print_file_32px.png"))); // NOI18N
        jButton4.setText("Veiw Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 300, 50));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setText("Location :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 80, 30));

        cmb_defLocation.setEditable(true);
        cmb_defLocation.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        cmb_defLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "==SELECT==", "ALL" }));
        cmb_defLocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb_defLocationFocusGained(evt);
            }
        });
        cmb_defLocation.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_defLocationPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cmb_defLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 400, 28));

        txt_locCode.setEditable(false);
        txt_locCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_locCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_locCodeFocusGained(evt);
            }
        });
        getContentPane().add(txt_locCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 80, 28));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_month1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_month1PopupMenuWillBecomeInvisible
        cmb_earn_type.setSelectedIndex(0);
    }//GEN-LAST:event_cmb_month1PopupMenuWillBecomeInvisible

    private void cmb_year1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_year1PopupMenuWillBecomeInvisible
        cmb_earn_type.setSelectedIndex(0);        //  days_per_month();
    }//GEN-LAST:event_cmb_year1PopupMenuWillBecomeInvisible

    private void cmb_earn_typePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_earn_typePopupMenuWillBecomeInvisible

    }//GEN-LAST:event_cmb_earn_typePopupMenuWillBecomeInvisible

    private void cmb_emp_typePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_emp_typePopupMenuWillBecomeInvisible

    }//GEN-LAST:event_cmb_emp_typePopupMenuWillBecomeInvisible

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

     

            String empType = cmb_emp_type.getSelectedItem().toString();

            try {

                String employeeType = "";
                if (empType.equals("ALL")) {
                    employeeType = " *";
                } else {
                    employeeType =  empType ;
                    System.out.println(employeeType);
                }
                
                 String earntype = "";
                if (cmb_earn_type.getSelectedIndex() == 1) {
                    earntype = " *";
                } else {
                    earntype = cmb_earn_type.getSelectedItem().toString();

                }

                String locCode = "";
                if (txt_locCode.getText().equals("ALL")) {
                    locCode = "T|E|D";
                } else {
                    locCode = txt_locCode.getText();

                }

                System.out.println(locCode);

                HashMap hm = new HashMap();
                hm.put("month", cmb_month1.getSelectedItem().toString());
                hm.put("year", cmb_year1.getSelectedItem().toString());
                hm.put("locCode", locCode);
                hm.put("deductionType", earntype);
                hm.put("rankCat", employeeType);

                String path = "Reports\\Salary_Earning_Report_Monthly.jrxml";
                String title = "Monthly Salary Earning Report";
                ReportView rv = new ReportView();
                rv.ReportView(path, hm, title);

            } catch (Exception e) {
                e.printStackTrace();
            }

       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmb_defLocationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb_defLocationFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_defLocationFocusGained

    private void cmb_defLocationPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_defLocationPopupMenuWillBecomeInvisible

        if (cmb_defLocation.getSelectedItem().equals("==SELECT==")) {

            txt_locCode.setText("NA");
            txt_locCode.setForeground(Color.red);

        } else if (cmb_defLocation.getSelectedItem().equals("ALL")) {
            txt_locCode.setForeground(Color.black);
            txt_locCode.setText("ALL");

        } else {
            txt_locCode.setForeground(Color.black);
            try {

                Statement st = DbConnection.getconnection().createStatement();
                ResultSet rs = st.executeQuery("SELECT * from location_reg where LocCode= '" + cmb_defLocation.getSelectedItem().toString() + "' OR LocName = '" + cmb_defLocation.getSelectedItem().toString() + "'");
                while (rs.next()) {

                    String name = rs.getString("LocName");
                    String code = rs.getString("LocCode");

                    txt_locCode.setText(code);
                    cmb_defLocation.setSelectedItem(name);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_cmb_defLocationPopupMenuWillBecomeInvisible

    private void txt_locCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_locCodeFocusGained

    }//GEN-LAST:event_txt_locCodeFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPT_Earnings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPT_Earnings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPT_Earnings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPT_Earnings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPT_Earnings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_defLocation;
    private javax.swing.JComboBox cmb_earn_type;
    private javax.swing.JComboBox cmb_emp_type;
    private javax.swing.JComboBox cmb_month1;
    private javax.swing.JComboBox cmb_year1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JTextField txt_locCode;
    // End of variables declaration//GEN-END:variables

    void print() {
        try {
            JRBeanCollectionDataSource bcds = new JRBeanCollectionDataSource(deductions);
            String path = "Reports\\deductions.jrxml";//Attendance_Summery_Single_Loc
            JasperReport jr = JasperCompileManager.compileReport(path);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, bcds);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clear() {
        EPFno = null;
        EmpName = null;
        Sal_Adv_01 = null;
        Sal_Adv_02 = null;
        Loan01 = null;
        Loan02 = null;
        Uniform = null;
        Shoe = null;
        welfare = null;
        meal = null;
        fine = null;
        rental = null;
        less_shift = null;
        other_deduc = null;
        death = null;
        paid10 = null;
        insuarance = null;

    }

}
