/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author SAPU
 */
public class User_register extends javax.swing.JFrame {

    /**
     * Creates new form User_reg
     */
    public User_register() {
        initComponents();

        rb_report.setSelected(true);
        lbl_test.setVisible(false);
        lbl_get_user_cat.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rb_admin = new javax.swing.JRadioButton();
        txt_userID = new javax.swing.JTextField();
        txt_Pass = new javax.swing.JPasswordField();
        txt_ConfirmPass = new javax.swing.JPasswordField();
        txt_name = new javax.swing.JTextField();
        rb_report = new javax.swing.JRadioButton();
        rb_de = new javax.swing.JRadioButton();
        rb_man = new javax.swing.JRadioButton();
        btn_user_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_test = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rb_sa = new javax.swing.JRadioButton();
        lbl_get_user_cat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setText("User Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 430, 10));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setText("User ID :-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 20));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setText("Password :-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 85, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setText("Confirm Password :-");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setText("User's Name :-");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 152, -1, 20));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setText("User Type :-");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 190, 80, 30));

        buttonGroup1.add(rb_admin);
        rb_admin.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        rb_admin.setText("Administrator");
        rb_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_adminMouseClicked(evt);
            }
        });
        getContentPane().add(rb_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        txt_userID.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txt_userID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userIDActionPerformed(evt);
            }
        });
        txt_userID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_userIDKeyPressed(evt);
            }
        });
        getContentPane().add(txt_userID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, 25));

        txt_Pass.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        getContentPane().add(txt_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 85, 140, 23));

        txt_ConfirmPass.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        getContentPane().add(txt_ConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 115, 140, 23));

        txt_name.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 260, 23));

        buttonGroup1.add(rb_report);
        rb_report.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        rb_report.setText(" Report Only ");
        rb_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_reportMouseClicked(evt);
            }
        });
        rb_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_reportActionPerformed(evt);
            }
        });
        getContentPane().add(rb_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 110, -1));

        buttonGroup1.add(rb_de);
        rb_de.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        rb_de.setText(" Data Entry");
        rb_de.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_deMouseClicked(evt);
            }
        });
        getContentPane().add(rb_de, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        buttonGroup1.add(rb_man);
        rb_man.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        rb_man.setText("Management Staff");
        rb_man.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_manMouseClicked(evt);
            }
        });
        getContentPane().add(rb_man, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        btn_user_save.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        btn_user_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        btn_user_save.setText("Save");
        btn_user_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_user_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, -1));

        btn_update.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save as.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        btn_delete.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eraser.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 110, -1));

        btn_clear.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 410, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 430, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 430, 10));

        lbl_test.setText("lbl_test");
        getContentPane().add(lbl_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add User Male-100.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 110, 110));

        buttonGroup1.add(rb_sa);
        rb_sa.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        rb_sa.setText("System Admin (All Privileges)");
        rb_sa.setEnabled(false);
        rb_sa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_saMouseClicked(evt);
            }
        });
        rb_sa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_saActionPerformed(evt);
            }
        });
        getContentPane().add(rb_sa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        lbl_get_user_cat.setText("lbl_usercat");
        getContentPane().add(lbl_get_user_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 80, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userIDActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_user_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_saveActionPerformed

        if (!txt_Pass.getText().equals(txt_ConfirmPass.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Password dosen't match. Please check!");
        } else if (txt_Pass.getText().isEmpty() | txt_ConfirmPass.getText().isEmpty() | txt_name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, " UserID , Password & User's Name can't be empty...!");
        } else {

            try {

                Statement st = DbConnection.getconnection().createStatement();
                st.executeUpdate("insert into user values ('" + txt_userID.getText() + "','" + txt_ConfirmPass.getText() + "','" + lbl_test.getText() + "','" + txt_name.getText() + "')");

                JOptionPane.showMessageDialog(rootPane, "Sucessfuly Saved...!");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_user_saveActionPerformed

    private void rb_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_adminMouseClicked
        if (rb_admin.isSelected()) {
            lbl_test.setText("");
            lbl_test.setText("admin");

        }
    }//GEN-LAST:event_rb_adminMouseClicked

    private void rb_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_reportMouseClicked
        if (rb_report.isSelected()) {
            lbl_test.setText("");
            lbl_test.setText("report");

        }  // TODO add your handling code here:
    }//GEN-LAST:event_rb_reportMouseClicked

    private void rb_deMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_deMouseClicked
        if (rb_de.isSelected()) {
            lbl_test.setText("");
            lbl_test.setText("data_entry");

        }    // TODO add your handling code here:
    }//GEN-LAST:event_rb_deMouseClicked

    private void rb_manMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_manMouseClicked
        if (rb_man.isSelected()) {
            lbl_test.setText("");
            lbl_test.setText("manager");

        }         // TODO add your handling code here:
    }//GEN-LAST:event_rb_manMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed

        // String uset_cat = MAIN.lbl_userCat.getText();
//        if(){}
        if (!txt_Pass.getText().equals(txt_ConfirmPass.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Password dosen't match. Please check!");
        } else if (txt_Pass.getText().isEmpty() | txt_ConfirmPass.getText().isEmpty() | txt_name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, " UserID , Password & User's Name can't be empty...!");
        } else {

            try {

                Statement st = DbConnection.getconnection().createStatement();
                st.executeUpdate("update user set Password='" + txt_ConfirmPass.getText() + "',UserCat='" + lbl_test.getText() + "',UserFullName='" + txt_name.getText() + "' where UserName='" + txt_userID.getText() + "'");

                JOptionPane.showMessageDialog(rootPane, "Sucessfuly Updated...!");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_userIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userIDKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {

            try {

                Statement st = DbConnection.getconnection().createStatement();
                ResultSet rs = st.executeQuery("select * from user where UserName='" + txt_userID.getText() + "'");
                while (rs.next()) {

                    txt_Pass.setText(rs.getString("Password"));
                    txt_ConfirmPass.setText(rs.getString("Password"));
                    txt_name.setText(rs.getString("UserFullName"));

                    String userCat = rs.getString("UserCat");
                    lbl_get_user_cat.setText(userCat);

                    if (userCat.equals("admin")) {
                        rb_admin.setSelected(true);
                    }
                    if (userCat.equals("manager")) {
                        rb_man.setSelected(true);
                    }
                    if (userCat.equals("data_entry")) {
                        rb_de.setSelected(true);
                    }
                    if (userCat.equals("report")) {
                        rb_report.setSelected(true);
                    }
                    if (userCat.equals("system_admin")) {
                        rb_sa.setSelected(true);
                    }
                    btn_user_save.setEnabled(false);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_txt_userIDKeyPressed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        btn_user_save.setEnabled(true);
        txt_ConfirmPass.setText("");
        txt_Pass.setText("");
        txt_name.setText("");
        txt_userID.setText("");
        rb_de.setSelected(false);
        rb_admin.setSelected(false);
        rb_man.setSelected(false);
        rb_report.setSelected(false);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void rb_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_reportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_reportActionPerformed

    private void rb_saMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_saMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_saMouseClicked

    private void rb_saActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_saActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_saActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_register().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_user_save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_get_user_cat;
    private javax.swing.JLabel lbl_test;
    private javax.swing.JRadioButton rb_admin;
    private javax.swing.JRadioButton rb_de;
    private javax.swing.JRadioButton rb_man;
    private javax.swing.JRadioButton rb_report;
    private javax.swing.JRadioButton rb_sa;
    private javax.swing.JPasswordField txt_ConfirmPass;
    private javax.swing.JPasswordField txt_Pass;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_userID;
    // End of variables declaration//GEN-END:variables
}
